function myplot3(xdata1, ydata1, zdata1)
%CREATEFIGURE(xdata1, ydata1, zdata1)
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata

%  Auto-generated by MATLAB on 10-Feb-2019 22:35:35

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create surf
surf(xdata1,ydata1,zdata1,'Parent',axes1);

% Create zlabel
zlabel({'option price'});

% Create ylabel
ylabel({'B'});

% Create xlabel
xlabel({'N'});

% Create title
title({'Option Price by N and B'});

view(axes1,[37.2 12.6]);
grid(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',11,'FontWeight','bold');
