function myplot1(Y1)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 10-Feb-2019 20:02:10

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(Y1);

% Create ylabel
ylabel({'option price'});

% Create xlabel
xlabel({'alpha'});

% Create title
title({'Option Price vs damping factor'});

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',13,'FontWeight','bold','XTick',[1 2 3 4 5 6 7 8],...
    'XTickLabel',{'0.01','0.25','0.5','1','1.5','5','10','20'});
