function myplot2(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6)
%CREATEFIGURE(X1, Y1, X2, Y2, X3, Y3, X4, Y4, X5, Y5, X6, Y6)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data
%  X3:  vector of x data
%  Y3:  vector of y data
%  X4:  vector of x data
%  Y4:  vector of y data
%  X5:  vector of x data
%  Y5:  vector of y data
%  X6:  vector of x data
%  Y6:  vector of y data

%  Auto-generated by MATLAB on 10-Feb-2019 20:46:27

% Create figure
figure1 = figure('NumberTitle','off','Name','LiveEditorFigure');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(X1,Y1);

% Create plot
plot(X2,Y2);

% Create plot
plot(X3,Y3);

% Create plot
plot(X4,Y4);

% Create plot
plot(X5,Y5);

% Create plot
plot(X6,Y6);

% Create ylabel
ylabel({'option price'});

% Create xlabel
xlabel({'K'});

% Create title
title({'Option Price vs K'});
legend();
box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',13,'FontWeight','bold');
