function myplot1(Y1)
%CREATEFIGURE(Y1)
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 17-Feb-2019 21:46:51

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create plot
plot(Y1);

% Create ylabel
ylabel({'Weights'});

% Create xlabel
xlabel({'Stocks'});

% Create title
title({'Weights of Stocks in Portfolio'});

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',13,'FontWeight','bold');
