function plot1(YMatrix1)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 01-Feb-2019 23:50:06

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','Left Riemann Rule');
set(plot1(2),'DisplayName','Midpoint Rule');
set(plot1(3),'DisplayName','Gaussian Quadrature');

% Create ylabel
ylabel({'Value'});

% Create xlabel
xlabel({'N'});

% Create title
title({' Calculation Error'},'FontSize',15);

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',12,'FontWeight','bold','XTick',[1 2 3 4],'XTickLabel',...
    {'5','10','50','100'});
% Create legend
legend(axes1,'show');

