function plot1(YMatrix1)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 26-Jan-2019 22:56:17

% Create figure
figure1 = figure('NumberTitle','off','Name','Figure');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1);
set(plot1(1),'DisplayName','st');
set(plot1(2),'DisplayName','portfolio payoff');
set(plot1(3),'DisplayName','call payoff');
set(plot1(4),'DisplayName','portfolio price');

% Create ylabel
ylabel({'price'});

% Create xlabel
xlabel({'draws'});

% Create title
title({'First 100 draws of simulation'});

% Create legend
legend(axes1,'show');

