function plot2(YMatrix1)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 26-Jan-2019 23:24:50

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1);
set(plot1(1),'DisplayName','portfolio payoff 1');
set(plot1(2),'DisplayName','portfolio payoff 2');

% Create ylabel
ylabel({'price'});

% Create xlabel
xlabel({'draws'});

% Create title
title({'Comparison of payoff between two portfolios'});

box(axes1,'on');
% Create legend
legend(axes1,'show');

